### ISSUE TITLE
'../dataset/Sprite/data.pkl' is not found.

### ISSUE THREAD

**Issue by Anonim5095** [JunwenBai/C-DSVAE#1]
Hi,
If you don't mind, could you share '../dataset/Sprite/data.pkl' with us?

**Comment by Anonim5095** [comment]
Sorry, I made it myself.

**Comment by littletake** [comment]
Thank you for sharing your programs.
I attempted to reproduce C-DSVAE but the above error occurred.
Could you share the program to create `data.pkl`?

**Comment by stepakar** [comment]
@hosh123 how did you get  'c_augs_train, c_augs_test = data['c_augs_train'], data['c_augs_test']
        m_augs_train, m_augs_test = data['m_augs_train'], data['m_augs_test']'
? I see how to get via Sprites the train/test sets and make a pickle, but not how to get these additional data...Thank you!

**Comment by JunwenBai** [comment]
Pls find it [here](https://drive.google.com/file/d/1PLaEmvn7xrA_rNPCUnWYJd-YQ3HW0EDo/view?usp=share_link).
