### ISSUE TITLE
About time variant latent z_rnn

### ISSUE THREAD

**Issue by heyuanYao-pku** [JunwenBai/C-DSVAE#2]
Hello, I have a question about the generation of time variant latent z_t

I think in the paper z_t depends on z_0,...,z_t-1.
```math
q(z_t|z_{<t}) = ...
```

while in your code latents are sampled independently, although with a rnn hidden state. 

```python
features, _ = self.z_rnn(lstm_out)
z_mean = self.z_mean(features)
z_logvar = self.z_logvar(features)
z_post = self.reparameterize(z_mean, z_logvar, random_sampling=True)
```

I think the randomness of previous latent are not introduced to the cureent latent, I'm wondering whether this is the same meaning with the paper?

**Comment by JunwenBai** [comment]
The lstm hidden states should capture that. Such sampling was also adopted in RWAE, S3VAE, etc.
