### ISSUE TITLE
'../dataset/Sprite/data.pkl' is not found.

### ISSUE THREAD

**Issue by littletake** [JunwenBai/C-DSVAE#3]
Thank you for sharing your programs.
I attempted to reproduce C-DSVAE but couldn't find the edited dataset(`data.pkl`).
If you might see #1, Could you share the dataset or the program to create it?

**Comment by tomoya-yamanokuchi** [comment]
@littletake I have same problem. Could you already solve this problem?

**Comment by JunwenBai** [comment]
Pls find it [here](https://drive.google.com/file/d/1PLaEmvn7xrA_rNPCUnWYJd-YQ3HW0EDo/view?usp=share_link).
